### ISSUE TITLE
ImportError: DLL load failed while importing Mania_Telemetry: The specified module could not be found.

### ISSUE THREAD

**Issue by CodyNinja1** [jonese1234/TM-Telemetry-Python#1]
I keep getting this error while running the example script:
`ImportError: DLL load failed while importing Mania_Telemetry: The specified module could not be found.`

How do I fix it?

**Comment by JuliusJacobitz** [comment]
This code works fine for me (also TM2020):
- put the downloadable Mania_Telemetry.pyd next to this file
```
from Mania_Telemetry import TrackmaniaTelemetry

while True:
     telemetry = TM.get()
     print(f"{telemetry.InputSteer}, {telemetry.InputGasPedal}, {telemetry.InputIsBraking}, {telemetry.SpeedMeter}")
```

**Comment by CodyNinja1** [comment]
sorry, i forgot to use python 3.8, thanks tho!
